---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/articles":
    get:
      summary: list articles
      tags:
      - Article
      parameters:
      - name: search
        in: query
        description: To search phrase in title or body of Article
        schema:
          type: string
      - name: status
        in: query
        schema:
          type: string
          enum:
          - unpublished
          - published
        description: 'To filter Article by status: published/unpublished'
      - name: author
        in: query
        description: To search Article by author name
        schema:
          type: string
      - name: tags
        in: query
        description: To search Article by tag name
        schema:
          type: string
      - name: order
        in: query
        description: To sort Articles by title in ascending(asc) or descending(decs)
          order
        schema:
          type: string
      responses:
        '200':
          description: successful
    post:
      summary: create article
      tags:
      - Article
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                author_id:
                  type: integer
              required:
              - title
              - body
              - author_id
              - status
  "/api/v1/articles/{id}":
    parameters:
    - name: id
      in: path
      description: article id
      required: true
      schema:
        type: string
    get:
      summary: show article with comments
      tags:
      - Article
      responses:
        '200':
          description: successful
    patch:
      summary: update article
      tags:
      - Article
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                  enum:
                  - unpublished
                  - published
              required:
              - title
              - body
              - status
    put:
      summary: update article
      tags:
      - Article
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                  enum:
                  - unpublished
                  - published
              required:
              - title
              - body
              - status
    delete:
      summary: delete article
      tags:
      - Article
      responses:
        '204':
          description: successful
  "/api/v1/comments":
    get:
      summary: list comments
      tags:
      - Comment
      parameters:
      - name: limit
        in: query
        description: To show last comments
        schema:
          type: integer
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      tags:
      - Comment
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                author_id:
                  type: integer
                article_id:
                  type: integer
              required:
              - body
              - author_id
              - article_id
  "/api/v1/comments/{id}":
    parameters:
    - name: id
      in: path
      description: comment id
      required: true
      schema:
        type: string
    get:
      summary: show comment
      tags:
      - Comment
      responses:
        '200':
          description: successful
    patch:
      summary: update comment
      tags:
      - Comment
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                  enum:
                  - unpublished
                  - published
              required:
              - body
              - status
    put:
      summary: update comment
      tags:
      - Comment
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                  enum:
                  - unpublished
                  - published
              required:
              - body
              - status
    delete:
      summary: delete comment
      tags:
      - Comment
      responses:
        '204':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
